stages:
  - release

default:
  image: node:lts
  cache: &cache
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store

before_script:
  - npm config set "//gitlab.com/api/v4/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
  - npm config set "//gitlab.com/api/v4/projects/${KNACK_REPO_ID}/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
  - npm install -g pnpm@7
  - pnpm config set store-dir .pnpm-store
  - pnpm install --frozen-lockfile


variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

publish:
  stage: release
  script:
    - pnpm build
    - pnpm semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
