stages:
  - release

before_script:
  - npm config set "//gitlab.com/api/v4/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
  - npm config set "//gitlab.com/api/v4/projects/${KNACK_REPO_ID}/packages/npm/:_authToken" "${CI_JOB_TOKEN}"
  - yarn install


variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

publish:
  image: node:14
  stage: release
  cache:
    paths:
      - .yarn
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
