yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "mammoth@*":
    dependencies:
      "util": "*"
  "lop@*":
    dependencies:
      "util": "*"
  "readable-stream@*":
    dependencies:
      "events": "*"
  "sax@*":
    dependencies:
      "string_decoder": "*"
  "stream-browserify@*":
    dependencies:
      "events": "*"
